---
title: "COHb Project Plan"
#subtitle: "Carbon Monoxide Exposure Calculation from Carboxyhemoglobin Blood Level"
#author: "Phillip Toone"
date: "9/19/2018 (First Draft)"
output: pdf_document
---

## Background

The Salt Lake Technical Center currently performs calculations to determine employee exposure to carbon monoxide (CO) based upon employee post exposure carboxyhemoglobin (COHb) blood concentration and other exposure details.  This calculation is performed with a program written by Mike Rose in the late 1990s.  The user interface for this program is DOS based and relatively awkward to use compared to modern standards.  More importantly, this program does not run on modern computers using a 64 bit operating system.  Finally, the method for performing this calculation is not published to the public as a recognized OSHA method.

## Objectives

* Create a user friendly GUI based program for performing carboxyhemoglobin calculations that generates a PDF report of the results.

* Create a fully validated method that explains how these calculations are performed.

## Scope

* The program will utilize the R programing language.

* An R library will be perform the core calculations.

* The Shiny R package will be used to develop the GUI.

* R markdown will be used to create a template for generating a PDF report for each sample.

* The GUI will read legacy PRN files but will save and load future projects as CSV files.

* The method will be written in R markdown.

## Timeframe

The following timeframe is a rough estimation considering that a significant portion of the work has already been accomplished.

| Phase         | Weeks |
| ------------- |:-----:|
| Create and validate R library for core calculations  |  done |
| Finish GUI  | 1 |
| Work with stakeholders to determine details of model parameters  | 1 |
| Finish R Markdown template for report generation  | 1 |
| Finish writting method  | 1 |

## Resources

Development of the PDF tempate and the method in R markdown requires MikTex to be installed on a developement maching if a Windows based operating system is used for development.  The following list of options are provided as a solution to this obstacle.

* Development can be accomplished while working from home on a personally owned computer where all development software is already installed and internet access is available.

* Develpoment can be accomplished at the SLTC on a personally owned computer that is NOT connected to the OSHA network. Internet access can be provided to the computer as needed with a MiFi type Wi-Fi hotspot like what is currently used by HRT staff.  This can be a personally owned device or a government owned device like what is currently provided to HRT staff.

* Development can be accomplished on a government procured computer running a Linux operating system. Internet can be provided to this computer though the STLC laboratory network or a MiFi type Wi-Fi hotspot as described in the previous option.

Journal articles relevent to carboxyhemoglobin and previous development efforts by Mike Rose have all been archived onto the Alfresco document management system.  Until recently this server has been functioning without a problem on the laboratory network similar to servers like Batman and Widowmaker that host services like Paradigm and LISA.  This server will need to be reconnected to the network to provide access to the documents necessary for the success of this project.

## Budget

If personal equipment is allowed to be used for this project it is not anticipated that this project will require procurment of any resources.

## Stakeholders

| Stakeholders   | Role |
| ------------- |-----:|
| Phillip Toone  |  Project Developer |
| Phil Smith  |  Project Authorizer |
| Jon Rima  |  COHb Manager |
| Scott Jones  |  COHb Analyst |

## Evaluation

Current library and GUI files for this project exist on the [SLTC github page](https://github.com/SaltLakeTechnicalCenter/COHb).  Github will continue to serve as the central repository for all of the code, documentation, methods, project status, and other relevent work product related to this project.  Emails detailing the current status of the project and any obstacles encountered will be sent to the stakeholders as necessary.

## Authorization

\vspace{50pt}


\noindent\rule{10cm}{0.4pt} \hspace{50pt} \noindent\rule{5cm}{0.4pt}

Phil Smith \hspace{300pt} Date
